controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_attendee_list:
    path: /list
    controller: App\Controller\AttendeeController::list
    methods: [GET]
